# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # there are reference to (Kestrel 1) source code in the current doc
      # need to install Kestrel 1 to resolve the reference
      # readthedocs shallow clone the repo, need to get the develop_v1 branch
      - git remote set-branches origin develop_v1
      - git fetch --depth 1 origin develop_v1
      - git checkout develop_v1
      - make install
      - git checkout develop

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - epub

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
